name: MacOS

on:
  [push, pull_request]

env:
  QT_VERSION: 5.15.2

jobs:
  macos_build:
    name: Build Relight (MacOS)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        cache: true
        version: ${{ env.QT_VERSION }}
    - name: Install dependencies
      run: |
        bash build_scripts/${{ runner.os }}/0_setup_env.sh
    - name: Configure and Build
      run: |
        bash build_scripts/${{ runner.os }}/1_build.sh --use_brew_llvm
    - name: Deploy
      run: |
        bash build_scripts/${{ runner.os }}/2_deploy.sh
    - name: DMG
      run: |
        bash build_scripts/${{ runner.os }}/3_dmg.sh
    - name: Upload Relight Portable
      uses: actions/upload-artifact@v3
      with:
        name: relight_macos_portable
        path: install/ReLight*.app
    - name: Upload Relight DMG
      uses: actions/upload-artifact@v3
      with:
        name: relight_macos_dmg
        path: install/ReLight*.dmg
